name: Test Docker Build and Install

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          set -e  # Остановить выполнение при ошибках
          echo "Updating packages..."
          sudo apt update && sudo apt upgrade -y
          echo "Creating user 'aero'..."
          sudo useradd -s /bin/bash -d /opt/aero -m aero || echo "User 'aero' might already exist"
          echo "Configuring sudoers..."
          echo "aero ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/aero
          echo "Installing git..."
          sudo apt install git -y
          sudo mkdir -p /opt/aero
          sudo chown -R aero:aero /opt/aero

      - name: Clone OpenVair repository
        run: |
          echo "Cloning OpenVair repository..."
          sudo -u aero git clone https://github.com/tihon49/test.git /opt/aero/openvair

      - name: Modify config file
        run: |
          echo "Modifying config file..."
          sudo -u aero sed -i "/\[default_user\]/,/^$/s/^login = .*/login = 'userrrr77'/; s/^password = .*/password = 'passsss77'/" /opt/aero/openvair/project_config.toml

      - name: Run installation script
        run: |
          echo "Running installation script..."
          sudo -u aero bash /opt/aero/openvair/install.sh

