name: Test Docker Build and Install

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo useradd -s /bin/bash -d /opt/aero -m aero
          sudo chmod +x /opt/aero
          echo "aero ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/aero
          sudo -u aero -i
          sudo apt install git -y
          git clone https://github.com/Aerodisk/openvair.git

      - name: Modify config file
        run: |
          sed -i "/\[default_user\]/,/^$/s/^login = .*/login = 'userrrr77'/; s/^password = .*/password = 'passsss77'/" /opt/aero/openvair/project_config.toml

      - name: Run installation script
        run: |
          ./openvair/install.sh

